### ISSUE TITLE
Fix Eslint issues on init

### ISSUE THREAD

**Issue by Epenance** [Novicell/novicell-cli#15]
When generating a new project we get some Eslint issues

```
/Applications/web/wutwut/layouts/error.vue
  28:0  error  Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

  10 |   },
  11 | })
> 12 | export default class ErrorLayout extends Vue {
     | ^
  13 |   @Prop() error!: any;
  14 | 
  15 |   get statusCode() {

/Applications/web/wutwut/mixins/GridEditorMixin.vue
  9:11  error  Parsing error: Unexpected token

   7 |     default: {},
   8 |   })
>  9 |   viewModel!: any;
     |            ^
  10 | 
  11 |   @Prop({
  12 |     default: 12,
```

**Comment by ankeris** [comment]
@Epenance what commands did you run in order to get this? I am having hard time reproducing it.

I am running:
1) `node dist/index.js init` - no lint errors whatsoever 
2) then after project initializes, i run `npm run build` - no lint errors

**Comment by Epenance** [comment]
Think i just used npx

**Comment by Epenance** [comment]
```bash
➜  web npx @novicell/cli init
npx: installed 62 in 3.028s
? Choose preferred setup option Default setup
? Destination path:  ./wutwut
? Project name:  wutwut
? Project description:  
? Author:  Novicell
```

**Comment by Dan9boi** [comment]
can you take over on this task @Epenance ?

**Comment by Epenance** [comment]
Running the npx command I dont get any errors anymore, guess it might have been a fluke, however I get a few files failing if i manually run the linter afterwards.

We should fix the errors so a newly created project is not faulty when linting.
