### ISSUE TITLE
Rename EF[component]'s

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-cli#7]
We shouldn't ship with any components that contains client initials.
Please rename the *EFwhatever* components to not include the *EF*.
https://github.com/Novicell/novicell-cli/tree/master/resources/spa-cms-setup/components/common

Be aware that we should both rename the component, and all of the reference imports for the components!

Could we ask for the namespace on setup, and then use that namespace instead?
@Epenance @ankeris

**Comment by Epenance** [comment]
I agree we should not include anything with Client initials, the big questions is however if we should even include any of the components we currently are, or just leave the project empty?

**Comment by ankeris** [comment]
@Epenance - Good point about the components initially. My thought was that they represent as an example of how to work with the Headless.

@Dan9boi - I guess we can add the "Prefix" question on the setup. If we are even keeping components (?)

**Comment by Dan9boi** [comment]
Great idea with the prefix question!
I think we should keep the components for now atleast. The [prefix]Link.vue component is very important, as this is something we always need.
Can you make a PR @Epenance ?
